### ISSUE TITLE
PUT request not found.

### ISSUE THREAD

**Issue by Shosho85** [jamesfacts/suite_app#6]
@harimohanraj89 @DrRobotmck @williamfshaw @bigtone1284

User Story: As a user, I would like to see a list of all itineraries in a city, so I can view where my friends are going. 

Not Found Error: 
PUT http://localhost:9888/itineraries/1 404 (Not Found) bundle.js:16529

Description:
The issue is that when we run the function to get the user name results from the itinerary list in console log, it renders to the DOM correctly. 

However after rendering the items we expect, I see an error in the console - there is an errant PUT request to a URL that doesn't exist.

we went through all the files we worked on to see what is generating that PUT request (which should not be). Not sure where the execution of the PUT request is made in any of our code. It appears a Backbone method we use might also fire a put request but we can't find where.

**Comment by harimohanraj89** [comment]
- What is the `bundle.js` file? 
- Does the error only show up when you get all the users? 
- Is there more information in the error? Can you expand the error's drop down menu and find any extra information regarding which file is trigggering this errant PUT request?
